DROP TABLE IF EXISTS `cdr_fields_master`;
CREATE TABLE `cdr_fields_master` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `target_number` varchar(20) DEFAULT NULL COMMENT 'Airtel:Target No, VI:Target /A PARTY NUMBER, JIO:Calling Party Telephone Number',
  `b_party_number` varchar(20) DEFAULT NULL COMMENT 'Airtel:B Party No, VI:B PARTY NUMBER, JIO:Called Party Telephone Number',
  `call_type` varchar(50) DEFAULT NULL COMMENT 'Airtel:Call Type, VI:CALL_TYPE, JIO:Call Type',
  `connection_type` varchar(50) DEFAULT NULL COMMENT 'Airtel:TOC, VI:Type of Connection, JIO:N/A',
  `lrn_number` varchar(20) DEFAULT NULL COMMENT 'Airtel:LRN No, VI:LRN- B Party Number, JIO:LRN Called No',
  `lrn_tsp_lsa` varchar(100) DEFAULT NULL COMMENT 'Airtel:LRN TSP-LSA, VI:Translation of LRN, JIO:N/A',
  `call_date` date DEFAULT NULL COMMENT 'Airtel:Date, VI:Call date, JIO:Call Date',
  `call_time` time DEFAULT NULL COMMENT 'Airtel:Time, VI:Call Initiation Time, JIO:Call Time',
  `call_termination_time` time DEFAULT NULL COMMENT 'Airtel:N/A, VI:N/A, JIO:Call Termination Time',
  `duration_seconds` int DEFAULT NULL COMMENT 'Airtel:Dur(s), VI:Call Duration, JIO:Call Duration',
  `first_cgi` varchar(100) DEFAULT NULL COMMENT 'Airtel:First CGI, VI:First Cell Global Id, JIO:First Cell ID',
  `first_location_coords` varchar(50) DEFAULT NULL COMMENT 'Airtel:First CGI Lat/Long, VI:First BTS Location, JIO:N/A',
  `last_cgi` varchar(100) DEFAULT NULL COMMENT 'Airtel:Last CGI, VI:Last Cell Global Id, JIO:Last Cell ID',
  `last_location_coords` varchar(50) DEFAULT NULL COMMENT 'Airtel:Last CGI Lat/Long, VI:Last BTS Location, JIO:N/A',
  `smsc_number` varchar(20) DEFAULT NULL COMMENT 'Airtel:SMSC No, VI:SMS Centre Number, JIO:SMS Center Number',
  `service_type` varchar(50) DEFAULT NULL COMMENT 'Airtel:Service Type, VI:Service Type, JIO:N/A',
  `imei` varchar(20) DEFAULT NULL COMMENT 'Airtel:IMEI, VI:IMEI, JIO:IMEI',
  `imsi` varchar(20) DEFAULT NULL COMMENT 'Airtel:IMSI, VI:IMSI, JIO:IMSI',
  `call_forwarding_number` varchar(20) DEFAULT NULL COMMENT 'Airtel:Call Fow No, VI:Call Forwarding Number, JIO:Call Forwarding',
  `roaming_network` varchar(100) DEFAULT NULL COMMENT 'Airtel:Roam Nw, VI:Roaming Network/Circle, JIO:Roaming Circle Name',
  `msc_id` varchar(100) DEFAULT NULL COMMENT 'Airtel:SW & MSC ID, VI:MSC ID, JIO:N/A',
  `in_trunk_group` varchar(50) DEFAULT NULL COMMENT 'Airtel:IN TG, VI:In TG, JIO:N/A',
  `out_trunk_group` varchar(50) DEFAULT NULL COMMENT 'Airtel:OUT TG, VI:Out TG, JIO:N/A',
  `vowifi_first_ue_ip` varchar(50) DEFAULT NULL COMMENT 'Airtel:Vowifi First UE IP',
  `vowifi_first_port` varchar(10) DEFAULT NULL COMMENT 'Airtel:Port1',
  `vowifi_last_ue_ip` varchar(50) DEFAULT NULL COMMENT 'Airtel:Vowifi Last UE IP',
  `vowifi_last_port` varchar(10) DEFAULT NULL COMMENT 'Airtel:Port2',
  `operator` varchar(20) DEFAULT NULL COMMENT 'Operator name: AIRTEL, VI, or JIO',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_target_number` (`target_number`),
  KEY `idx_call_date` (`call_date`),
  KEY `idx_operator` (`operator`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;